apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deployment
  labels:
    app: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: tavo98/hasher
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  selector:
    app: hasher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80