apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng-deployment
  labels:
    app: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: tavo98/rng
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  selector:
    app: rng
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80